# Generated by Django 5.2.7 on 2025-11-03 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_seen_alter_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summarized_content', models.TextField(verbose_name='AI Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cache creation time')),
                ('status', models.CharField(default='Success', max_length=50, verbose_name='Processing status')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='api.post', verbose_name='The article is summarized')),
            ],
            options={
                'verbose_name': 'AI Summary',
                'verbose_name_plural': 'AI Summaries',
            },
        ),
    ]
