# Generated by Django 4.2 on 2025-11-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='image/default-user.jpg', null=True, upload_to='image/'),
        ),
    ]
