# Generated by Django 4.2 on 2026-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.FileField(blank=True, default='image/default-cover.jpg', null=True, upload_to='image/'),
        ),
    ]
